source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'IdramMerchantPayment_Example', :exclusive => true do
  pod 'IdramMerchantPayment', :path => '../'
end

target 'IdramMerchantPayment_Tests', :exclusive => true do
  pod 'IdramMerchantPayment', :path => '../'

  
end
